// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phvndlmnuksjohbrasvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodm5kbG1udWtzam9oYnJhc3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTgwNTksImV4cCI6MjA2MjQzNDA1OX0.r1MBeUhEWLU_KsmdmkiSf8erGMSisius4BKzV37LnWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);